name: Build project

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualizado a v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Actualizado a v4
      with:
        python-version: 3.10  # Versión de Python corregida

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile charly.py
        pyinstaller --onefile charly_gui.py

    - name: Archive build outputs
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: dist/
